- name: Verifier que le daemon Docker est bien installé
  hosts: localhost
  gather_facts: True
  become: yes
  tasks:
    - name: stop app    
      include: Exploitation_stop_app.yml

    - name: Créer répertoire /home/appli
      file:
        path: /home/appli
        state: directory
      mode: 0755

    - name: décompresser l'archive de l'application dans /home/appli
      unarchive:
        src: "/home/appli/app_{{ app_version }}.js.zip"
        dest: /home/appli/
        remote_src: yes 
    
    - name: Deposer le fichier systemD de configuration de notre application
      template:
        src: app.service.j2
        dest: /etc/systemd/system/app.service
      register: systemd

    - name: Reload du Daemon systemctl
      shell: systemctl daemon-reload
      
    - name: start app
      include: Exploitation_start_app.yml

    - name: tester que l'application fonctionne correctement
      uri:
        url: http://10.94.12.12:8081
        status_code: 200
      register: app_status
      ignore_errors: yes
    
    - name: Verifier que  Nginx est present sur le serveur
      yum:
        name: nginx
        state: present

    - name: Verifier que le service nginx est bien Enabled
      service:
        name: nginx
        enabled: yes

    - name: Deposer le fichier de configuration nginX de notre application
      template:
        src: app_nginx.conf.j2
        dest: /etc/nginx/conf.d/app_nginx.conf
      register: systemd

    - name: Redémarrage du service nginX
      service:
        name: nginx
        state: restarted

    - name: tester que l'application fonctionne correctement
      uri:
        url: http://10.94.12.12:8081
        status_code: 200
      register: app_status
      ignore_errors: yes

