- name: Verifier que le daemon Docker est bien installé
  hosts: localhost
  gather_facts: False
  become: yes
  tasks:
    - name: Créer répertoire /home/appli
      file:
        path: /home/appli
        state: directory
      mode: 0755

#    - name: télécharger l'application dans /home/appli
#      get_url:
#        url: https://github.com/devdenver/integration_continue/blob/master/app_v1.0.0.js.gz
#        dest: /home/appli
#      mode: 0755
 
    - name: décompresser l'archive de l'application dans /home/appli
      unarchive:
        src: /home/appli/app.tar.gz
        dest: /home/appli/
        remote_src: no

