- name: Verifier que le daemon Docker est bien installé
  hosts: dev
  gather_facts: False
  become: yes
  tasks:
   - name: creation du repertoire docker_by_ansible
     file:
       name: /home/appli/docker_by_ansible
       state: directory

   - name: copier le Dockerfile 
     template:
       src: Dockerfile.j2 
       dest: /home/appli/docker_by_ansible/Dockerfile

   - name: verifier que le service docker est bien lance
     service:
       name: docker.service
       state: started

   - name: Build an image locally
     docker_image:
       path: /home/appli/docker_by_ansible/
       name: "{{ tag_image }}"
       tag: "{{ docker_images_version }}"
